# Generated by Django 2.0.2 on 2019-10-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo'),
        ),
    ]
