# Generated by Django 2.0.2 on 2019-10-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['fechacurso'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.AddField(
            model_name='page',
            name='fechacurso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='codigo',
            field=models.CharField(max_length=200, verbose_name='Código'),
        ),
    ]
