# Generated by Django 2.0.2 on 2019-10-22 05:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191022_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='temariocurso',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Temario'),
        ),
    ]
