# Generated by Django 2.0.2 on 2019-10-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_temariocurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['fechacurso'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
    ]
