# Generated by Django 2.0.2 on 2019-10-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20191022_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='codigo',
            field=models.CharField(max_length=8, verbose_name='Código'),
        ),
    ]
