# Generated by Django 2.0.2 on 2019-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20191022_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='arancelcurso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Arancel'),
        ),
    ]
