# Generated by Django 2.0.2 on 2019-10-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_page_arancelcurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='arancelcurso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
