# Generated by Django 2.0.2 on 2019-10-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20191022_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='localizacioncurso',
            field=models.CharField(blank=True, help_text='HOLA', max_length=400, null=True, verbose_name='Localizacion (Coordenadas)'),
        ),
    ]
