# Generated by Django 2.0.2 on 2019-10-22 07:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_page_localizacioncurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='disertantescurso',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Disertantes'),
        ),
        migrations.AlterField(
            model_name='page',
            name='localizacioncurso',
            field=models.CharField(blank=True, help_text='Cómo obtener las coordenadas de un lugar <br> 1. ir a www.latlong.net <br> 2. Introducir la direccion: ej. Rioja 2045, Rosario, Santa Fe<br>3.Dar al boton Find <br> 4. Aparecera una marca azul en el mapa si ve que no esta exactamente haga doble click en la localizacion exacta<br>5. Listo copie la latitud y longitud tal cual.<br><br>En el campo de localizacion debe introducir de esta forma esos datos:<br>lat: -32.952917, lng: -60.655833', max_length=400, null=True, verbose_name='Localizacion (Coordenadas)'),
        ),
    ]
