# Generated by Django 2.0.2 on 2019-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20191022_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='arancelcurso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo 2 decimales si corresponde y usar la coma no el punto', max_digits=6, null=True, verbose_name='Arancel $'),
        ),
        migrations.AlterField(
            model_name='page',
            name='localizacioncurso',
            field=models.CharField(blank=True, help_text='Cómo obtener las coordenadas de un lugar <br> 1. ir a www.latlong.net <br> 2. Introducir la direccion: ej. Rioja 2045, Rosario, Santa Fe<br>3.Dar al boton Find <br> 4. Aparecera una marca azul en el mapa si ve que no esta exactamente haga doble click en la localizacion exacta<br>5. Listo copie la latitud y longitud tal cual.<br><br>En el campo de localizacion debe introducir de esta forma esos datos incluidos las llaves:<br>{lat: -32.952917, lng: -60.655833}', max_length=400, null=True, verbose_name='Localizacion (Coordenadas)'),
        ),
    ]
