# Generated by Django 2.0.2 on 2019-10-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20191022_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
    ]
