# Generated by Django 2.0.2 on 2019-10-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20191023_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='headerimg',
            field=models.ImageField(null=True, upload_to='projects', verbose_name='Imagen'),
        ),
    ]
