# Generated by Django 2.0.2 on 2019-10-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_page_headerimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='headerimg',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen'),
        ),
    ]
