# Generated by Django 2.0.2 on 2019-10-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20191030_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='headerimg',
            field=models.ImageField(blank=True, help_text='ATENCION!! ASEGURARSE QUE LA IMAGEN NO SUPERA LOS 710px DE ALTURA PARA GUARDAR LA PROPORCIONALIDAD.', null=True, upload_to='projects', verbose_name='Imagen'),
        ),
    ]
