# Generated by Django 2.0.2 on 2019-10-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0002_auto_20191027_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Suscriptor', 'verbose_name_plural': 'Suscriptores'},
        ),
    ]
