# Generated by Django 2.0.2 on 2019-10-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0004_auto_20191027_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='prono',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='prosi',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(help_text='Ej. Rosario 2000', max_length=100, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
