# Generated by Django 2.0.2 on 2019-10-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0006_auto_20191028_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='prono',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='prosi',
        ),
    ]
