# Generated by Django 2.0.2 on 2019-10-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0007_auto_20191028_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='procurador',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
