# Generated by Django 2.0.2 on 2019-10-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0009_auto_20191029_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Código del curso',
                'verbose_name_plural': 'Códigos de los cursos',
            },
        ),
    ]
