# Generated by Django 2.0.2 on 2019-10-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0010_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='codur',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
