# Generated by Django 2.0.2 on 2019-10-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0011_codigo_codur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='codur',
            field=models.CharField(max_length=7, verbose_name='Código del curso'),
        ),
    ]
