# Generated by Django 2.0.2 on 2019-10-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0013_auto_20191029_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={'verbose_name': 'Codigo Curso', 'verbose_name_plural': 'Codigo Cursos'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.PositiveSmallIntegerField(help_text='Dni válido ej. 22222222'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='procurador',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2),
        ),
    ]
