# Generated by Django 2.0.2 on 2019-10-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0015_auto_20191030_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(help_text='Dni válido ej. 22222222', max_length=8, unique=True),
        ),
    ]
