# Generated by Django 2.0.2 on 2019-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0016_auto_20191030_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='headerimg',
            field=models.ImageField(null=True, upload_to='projects', verbose_name='Imagen'),
        ),
    ]
