# Generated by Django 2.0.2 on 2019-10-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaformularios', '0017_persona_headerimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='headerimg',
        ),
    ]
